// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('irambi', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('irambi', async function() {
    await driver.get("https://app.durable.co/website/builder")
    await driver.manage().window().setRect({ width: 1103, height: 1012 })
    await driver.switchTo().frame(0)
    await driver.switchTo().defaultContent()
    await driver.switchTo().frame(0)
    await driver.switchTo().defaultContent()
    await driver.switchTo().frame(0)
  })
})
